// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	account.proto
	karma.proto
	user_agent.proto

It has these top-level messages:
	Account
*/
package data

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// Account describes a reddit account. Some of these fields are never filled
// for accounts other than the authenticated one. (You can't count someone
// else's inbox messages.)
type Account struct {
	Name             *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id               *string  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	LinkKarma        *int32   `protobuf:"varint,3,opt,name=link_karma" json:"link_karma,omitempty"`
	CommentKarma     *int32   `protobuf:"varint,4,opt,name=comment_karma" json:"comment_karma,omitempty"`
	IsMod            *bool    `protobuf:"varint,5,opt,name=is_mod" json:"is_mod,omitempty"`
	HasModMail       *bool    `protobuf:"varint,6,opt,name=has_mod_mail" json:"has_mod_mail,omitempty"`
	HasMail          *bool    `protobuf:"varint,7,opt,name=has_mail" json:"has_mail,omitempty"`
	InboxCount       *int32   `protobuf:"varint,8,opt,name=inbox_count" json:"inbox_count,omitempty"`
	Created          *float64 `protobuf:"fixed64,9,opt,name=created" json:"created,omitempty"`
	CreatedUtc       *float64 `protobuf:"fixed64,10,opt,name=created_utc" json:"created_utc,omitempty"`
	IsGold           *bool    `protobuf:"varint,11,opt,name=is_gold" json:"is_gold,omitempty"`
	GoldCredits      *int32   `protobuf:"varint,12,opt,name=gold_credits" json:"gold_credits,omitempty"`
	GoldExpiration   *float64 `protobuf:"fixed64,13,opt,name=gold_expiration" json:"gold_expiration,omitempty"`
	Over_18          *bool    `protobuf:"varint,14,opt,name=over_18" json:"over_18,omitempty"`
	HasVerifiedEmail *bool    `protobuf:"varint,15,opt,name=has_verified_email" json:"has_verified_email,omitempty"`
	HideFromRobots   *bool    `protobuf:"varint,16,opt,name=hide_from_robots" json:"hide_from_robots,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}

func (m *Account) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Account) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Account) GetLinkKarma() int32 {
	if m != nil && m.LinkKarma != nil {
		return *m.LinkKarma
	}
	return 0
}

func (m *Account) GetCommentKarma() int32 {
	if m != nil && m.CommentKarma != nil {
		return *m.CommentKarma
	}
	return 0
}

func (m *Account) GetIsMod() bool {
	if m != nil && m.IsMod != nil {
		return *m.IsMod
	}
	return false
}

func (m *Account) GetHasModMail() bool {
	if m != nil && m.HasModMail != nil {
		return *m.HasModMail
	}
	return false
}

func (m *Account) GetHasMail() bool {
	if m != nil && m.HasMail != nil {
		return *m.HasMail
	}
	return false
}

func (m *Account) GetInboxCount() int32 {
	if m != nil && m.InboxCount != nil {
		return *m.InboxCount
	}
	return 0
}

func (m *Account) GetCreated() float64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

func (m *Account) GetCreatedUtc() float64 {
	if m != nil && m.CreatedUtc != nil {
		return *m.CreatedUtc
	}
	return 0
}

func (m *Account) GetIsGold() bool {
	if m != nil && m.IsGold != nil {
		return *m.IsGold
	}
	return false
}

func (m *Account) GetGoldCredits() int32 {
	if m != nil && m.GoldCredits != nil {
		return *m.GoldCredits
	}
	return 0
}

func (m *Account) GetGoldExpiration() float64 {
	if m != nil && m.GoldExpiration != nil {
		return *m.GoldExpiration
	}
	return 0
}

func (m *Account) GetOver_18() bool {
	if m != nil && m.Over_18 != nil {
		return *m.Over_18
	}
	return false
}

func (m *Account) GetHasVerifiedEmail() bool {
	if m != nil && m.HasVerifiedEmail != nil {
		return *m.HasVerifiedEmail
	}
	return false
}

func (m *Account) GetHideFromRobots() bool {
	if m != nil && m.HideFromRobots != nil {
		return *m.HideFromRobots
	}
	return false
}
