// Code generated by protoc-gen-go.
// source: user_agent.proto
// DO NOT EDIT!

package data

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// UserAgent describes a non-user entity controlling a reddit account. This
// information is REQUIRED according the reddit api rules.
type UserAgent struct {
	UserAgent        *string `protobuf:"bytes,1,req,name=user_agent" json:"user_agent,omitempty"`
	ClientId         *string `protobuf:"bytes,2,req,name=client_id" json:"client_id,omitempty"`
	ClientSecret     *string `protobuf:"bytes,3,req,name=client_secret" json:"client_secret,omitempty"`
	Username         *string `protobuf:"bytes,4,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,5,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserAgent) Reset()         { *m = UserAgent{} }
func (m *UserAgent) String() string { return proto.CompactTextString(m) }
func (*UserAgent) ProtoMessage()    {}

func (m *UserAgent) GetUserAgent() string {
	if m != nil && m.UserAgent != nil {
		return *m.UserAgent
	}
	return ""
}

func (m *UserAgent) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *UserAgent) GetClientSecret() string {
	if m != nil && m.ClientSecret != nil {
		return *m.ClientSecret
	}
	return ""
}

func (m *UserAgent) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *UserAgent) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}
