// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package rsort

import "github.com/turnage/graw/internal/data"

type messagesThingImpl struct {
	e *data.Message
}

func (g messagesThingImpl) Name() string { return g.e.Name }

func (g messagesThingImpl) Birth() uint64 { return g.e.CreatedUTC }

func messagesAsThings(gs []*data.Message) []redditThing {
	things := make([]redditThing, len(gs))
	for i, g := range gs {
		things[i] = &messagesThingImpl{g}
	}
	return things
}
