// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package handlers

import "github.com/turnage/graw/internal/data"

// CommentHandler processes Reddit comments.
type CommentHandler interface {
	// HandleComment processes a Reddit comment.
	HandleComment(p *data.Comment) error
}

type commentHandler struct {
	handler func(p *data.Comment) error
}

func (h *commentHandler) HandleComment(comment *data.Comment) error {
	return h.handler(comment)
}

// CommentHandlerFunc returns a CommentHandler using the given function.
func CommentHandlerFunc(f func(e *data.Comment) error) CommentHandler {
	return &commentHandler{f}
}
