// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package handlers

import "github.com/turnage/graw/internal/data"

// PostHandler processes Reddit posts.
type PostHandler interface {
	// HandlePost processes a Reddit post.
	HandlePost(p *data.Post) error
}

type postHandler struct {
	handler func(p *data.Post) error
}

func (h *postHandler) HandlePost(post *data.Post) error {
	return h.handler(post)
}

// PostHandlerFunc returns a PostHandler using the given function.
func PostHandlerFunc(f func(e *data.Post) error) PostHandler {
	return &postHandler{f}
}
